# Generated by Django 6.0 on 2026-01-01 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_title', models.CharField(max_length=20)),
                ('B_slug', models.SlugField(max_length=30, unique_for_date='publish')),
                ('B_content', models.TextField(blank=True)),
                ('B_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('B_created', models.DateTimeField(auto_now_add=True)),
                ('B_updated', models.DateTimeField(auto_now=True)),
                ('B_status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('B_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
