# Generated by Django 6.0.1 on 2026-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='B_slug',
            field=models.SlugField(max_length=30, unique_for_date='B_publish'),
        ),
    ]
