# Generated by Django 6.0 on 2025-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=100)),
                ('t_desc', models.TextField()),
                ('t_completed', models.BooleanField(default=False)),
                ('t_created_at', models.DateTimeField(auto_now_add=True)),
                ('t_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
